export const  ADD_BOOKS = 'ADD_BOOKS';
export const DELETE_BOOK = 'DELETE_BOOK';
export const FETCH_BOOKS_PENDING = 'FETCH_BOOKS_PENDING';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOKS_ERROR= 'FETCH_BOOKS_ERROR';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const CLEAR_BOOKS = 'CLEAR_BOOKS'